2018-08-08 21:57:40,741 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 10:01:52,265 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 10:04:31,286 - all - INFO - views.py line:119-- timestamp : 1533780270698 
2018-08-09 10:04:37,546 - all - ERROR - views.py line:61-- <QuerySet []> 
2018-08-09 10:06:52,336 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 10:06:54,150 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 10:10:46,665 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 10:10:48,381 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 10:11:55,380 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 10:11:57,136 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 10:12:16,743 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 10:12:18,347 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 10:13:54,875 - django.request - ERROR - exception.py line:118-- Internal Server Error: /day/upload/ 
Traceback (most recent call last):
  File "E:\common\Python\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\common\Python\lib\site-packages\django\bin\iot\day\views.py", line 198, in upload
    print(type(rowValues[10]))
IndexError: list index out of range
2018-08-09 10:27:39,873 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 10:27:41,484 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 10:27:49,760 - django.request - ERROR - exception.py line:118-- Internal Server Error: /day/upload/ 
Traceback (most recent call last):
  File "E:\common\Python\lib\site-packages\django\utils\datastructures.py", line 77, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'my_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\common\Python\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\common\Python\lib\site-packages\django\bin\iot\day\views.py", line 204, in upload
    f = request.FILES['my_file']
  File "E:\common\Python\lib\site-packages\django\utils\datastructures.py", line 79, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'my_file'
2018-08-09 10:28:08,299 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 10:28:09,973 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 10:28:15,287 - django.request - ERROR - exception.py line:118-- Internal Server Error: /day/upload/ 
Traceback (most recent call last):
  File "E:\common\Python\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\common\Python\lib\site-packages\django\bin\iot\day\views.py", line 216, in upload
    print(type(rowValues[10]))
IndexError: list index out of range
2018-08-09 10:39:56,585 - django.request - ERROR - exception.py line:118-- Internal Server Error: /day/upload/ 
Traceback (most recent call last):
  File "E:\common\Python\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\common\Python\lib\site-packages\django\bin\iot\day\views.py", line 216, in upload
    print(type(rowValues[10]))
IndexError: list index out of range
2018-08-09 10:40:01,828 - django.request - ERROR - exception.py line:118-- Internal Server Error: /day/upload/ 
Traceback (most recent call last):
  File "E:\common\Python\lib\site-packages\django\core\handlers\exception.py", line 35, in inner
    response = get_response(request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "E:\common\Python\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\common\Python\lib\site-packages\django\bin\iot\day\views.py", line 216, in upload
    print(type(rowValues[10]))
IndexError: list index out of range
2018-08-09 10:40:41,970 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 10:40:46,862 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 10:41:21,038 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 10:41:22,758 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 10:43:19,048 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 10:45:27,137 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 10:46:30,232 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 10:46:32,051 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 10:46:55,113 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 10:46:56,697 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 10:47:05,317 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 10:47:06,949 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 10:47:36,236 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 10:47:37,840 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 10:47:54,796 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 10:47:56,479 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 10:48:03,845 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 10:48:05,555 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 10:48:20,135 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 10:48:21,661 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 10:48:39,105 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 10:48:40,705 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 10:49:27,253 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 10:49:28,876 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 10:49:45,977 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 10:49:47,510 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 10:49:50,091 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 10:49:51,783 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 10:51:15,835 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 10:51:17,399 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 10:52:33,182 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 10:52:34,711 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 10:54:16,406 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 10:54:17,921 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 10:55:13,559 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 10:55:15,163 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 10:55:44,254 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 10:55:46,120 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 10:56:34,376 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 10:57:09,844 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 10:57:19,423 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 10:57:21,011 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 10:57:21,508 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 10:57:22,064 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 10:57:47,732 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 10:57:49,540 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 10:58:20,241 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 10:58:22,039 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 10:58:24,303 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 10:58:24,845 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 10:58:30,257 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 10:58:30,769 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 10:58:38,115 - apscheduler.threadpool - INFO - threadpool.py line:52-- Started thread pool with 0 core threads and 20 maximum threads 
2018-08-09 10:58:38,757 - root - INFO - threadpool.py line:111-- Shutting down thread pool 
2018-08-09 11:05:15,633 - all - INFO - views.py line:58-- get news : 
2018-08-09 11:05:15,643 - all - INFO - views.py line:147-- get news : 
2018-08-09 11:05:15,677 - all - INFO - views.py line:128-- get news : 
2018-08-09 11:05:15,689 - all - INFO - views.py line:111-- get news : 
2018-08-09 11:05:19,654 - all - INFO - views.py line:25-- get news : 
2018-08-09 11:05:19,657 - all - INFO - views.py line:128-- get news : 
2018-08-09 11:05:19,698 - all - INFO - views.py line:111-- get news : 
2018-08-09 11:05:19,699 - all - INFO - views.py line:147-- get news : 
2018-08-09 11:05:27,858 - all - INFO - views.py line:128-- get news : 
2018-08-09 11:05:27,859 - all - INFO - views.py line:25-- get news : 
2018-08-09 11:05:27,860 - all - INFO - views.py line:147-- get news : 
2018-08-09 11:05:27,862 - all - INFO - views.py line:111-- get news : 
2018-08-09 11:05:32,701 - all - INFO - views.py line:25-- get news : 
2018-08-09 11:05:32,706 - all - INFO - views.py line:128-- get news : 
2018-08-09 11:05:32,707 - all - INFO - views.py line:147-- get news : 
2018-08-09 11:05:32,710 - all - INFO - views.py line:111-- get news : 
